export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_FAILURE = "AUTHENTICATE_USER_FAILURE";

export const AUTHORIZE_USER = "AUTHORIZE_USER";
export const AUTHORIZE_USER_SUCCESS = "AUTHORIZE_USER_SUCCESS";
export const AUTHORIZE_USER_FAILURE = "AUTHORIZE_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const CONFIRM_REGISTER_USER = "CONFIRM_REGISTER_USER";
export const RESEND_CONFIRM_CODE = "RESEND_CONFIRM_CODE";


export const CHECK_IF_NOT_REGISTERED = "CHECK_IF_NOT_REGISTERED";
export const CHECK_SUCCESS = "CHECK_SUCCESS";
export const CHECK_FAILED = "CHECK_FAILED";
