export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_CATEGORY_TAGS = "GET_CATEGORY_TAGS";
export const GET_CATEGORY_TAGS_SUCCESS = "GET_CATEGORY_TAGS_SUCCESS";
