export const GET_COMMENT_REPLIES = "GET_COMMENT_REPLIES";
export const GET_COMMENT_REPLIES_SUCCESS = "GET_COMMENT_REPLIES_SUCCESS";
export const GET_COMMENT_REPLIES_FAILURE = "GET_COMMENT_REPLIES_FAILURE";
