export const TOKEN_KEY = "token";
export * as AuthTypes from "./authConstant";
export * as UITypes from "./uiConstant";
export * as PostTypes from "./postConstant";
export * as TagTypes from "./tagConstant";
export * as CommentTypes from "./commentConstant";
export * as UserTypes from "./userConstant";
export * as URL from "./urlConstant";
export * as CategoryTypes from "./categoryConstant";
export * as AppConstant from "./appConstant";
