export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const FETCH_DATA_POST_DETAILS_PAGE = "FETCH_DATA_POST_DETAILS_PAGE";
export const FETCH_DATA_HOME_PAGE = "FETCH_DATA_HOME_PAGE";
export const FETCH_DATA_POST_PAGE = "FETCH_DATA_POST_PAGE";
export const FETCH_DATA_ADMIN_POSTS_PAGE = "FETCH_DATA_ADMIN_POSTS_PAGE";
export const FETCH_DATA_PROFILE_PAGE = "FETCH_DATA_PROFILE_PAGE";
export const FETCH_DATA_SEARCH_PAGE = "FETCH_DATA_SEARCH_PAGE";
export const FETCH_DATA_TAG_PAGE = "FETCH_DATA_TAG_PAGE";
export const FETCH_DATA_USER_INFO_PAGE = "FETCH_DATA_USER_INFO_PAGE";
export const FETCH_DATA_CATEGORY_PAGE = "FETCH_DATA_CATEGORY_PAGE";
export const FETCH_DATA_ADMIN_CATEGORIES_PAGE = "FETCH_DATA_ADMIN_CATEGORIES_PAGE";
export const FETCH_DATA_ADMIN_USERS_PAGE = "FETCH_DATA_ADMIN_USERS_PAGE";
